name: get-json-property
description: Get a property from a json file with dot notation

# Examples:
# prop_path: version
# prop_path: devDependencies.@salesforce/dev-scripts

inputs:
  path:
    required: true
    description: Json file to look up prop (package.json)
  prop_path:
    required: true
    description: dot notation property to find (version)

outputs:
  prop:
    description: The value of the prop_path
    value: ${{ steps.parse.outputs.prop }}

runs:
  using: "composite"
  steps:
    - name: Get property from json file
      id: parse
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          try {
            const fs = require('fs')

            var path = process.env.INPUTS_PATH;
            var propPath = process.env.INPUTS_PROP_PATH;

            const json = JSON.parse(fs.readFileSync(path))

            // https://stackoverflow.com/a/43849204
            const result = propPath.split('.').reduce((p,c)=>p&&p[c]||null, json)

            if (result) {
              core.setOutput('prop', result)
            } else {
              core.setFailed(`Property '${propPath}' not found in '${path}'`)
            }
          } catch(err) {
            core.setFailed(err)
          }
      env:
        INPUTS_PATH: ${{ inputs.path }}
        INPUTS_PROP_PATH: ${{ inputs.prop_path }}
