name: gitConfig
description: "Sets git username/email and push behavior"

inputs:
  username:
    description: "Github username to set as `user.name`. TIP: Use getGithubUserInfo to look up username from a Github token."
    required: true
  email:
    description: "Github email to set as `user.email`. TIP: Use getGithubUserInfo to look up email from a Github token."
    required: true

runs:
  using: composite
  steps:
    - name: Set git config
      shell: bash
      run: |
        git config --global push.default current
        git config --global user.name "$INPUTS_USERNAME"
        git config --global user.email "$INPUTS_EMAIL"
      env:
        INPUTS_USERNAME: ${{ inputs.username }}
        INPUTS_EMAIL: ${{ inputs.email }}
