name: Determine node versions
description: "Get all the supported node versions"
inputs:
  nodeVersionOverride:
    description: Set node to a specific Semver version
    required: false
outputs:
  nodeVersions:
    description: Node versions to be consumed by a workflow matrix
    value: ${{ steps.node-versions.outputs.nodeVersions }}
runs:
  using: 'composite'
  steps:
    # Note: this is not typically how you would run javascript in an action
    # This is need so that we can get the correct node version used elsewhere
    - name: logging
      shell: bash
      run: |
        echo "nodeVersionOverride: ${{ inputs.nodeVersionOverride || 'lts/*' }}"
        echo "action_path: ${{ github.action_path }}"
        echo "action path env var: $GITHUB_ACTION_PATH"
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.nodeVersionOverride || 'lts/*' }}
    - name: Run main script
      shell: bash
      id: node-versions
      run: node "$GITHUB_ACTION_PATH/dist/index.js"

