name: Determine node versions
description: "Get all the supported node versions"
inputs:
  nodeVersionOverride:
    description: Semver version to set version and version-1
    default: 'lts/*'
    required: false
outputs:
  nodeVersions:
    description: Node versions to be consumed by a workflow matrix
    value: ${{ steps.node-versions.outputs.nodeVersions }}
runs:
  using: 'composite'
  steps:
    # Note: this is not typically how you would run javascript in an action
    # This is need so that we can get the correct node version used elsewhere
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.nodeVersionOverride }}
    - name: Run main script
      shell: bash
      id: node-versions
      run: node ${{ github.action_path }}/dist/index.js

