name: ctcOpen
description: Open a CTC case for a release

inputs:
  SF_CHANGE_CASE_SFDX_AUTH_URL:
    description: Auth URL
    required: true
  SF_CHANGE_CASE_TEMPLATE_ID:
    description: Change Case template ID
    required: true
  SF_CHANGE_CASE_CONFIGURATION_ITEM:
    description: Change Case config item
    required: true
  SVC_CLI_BOT_GITHUB_TOKEN:
    description: Github token
    required: true
  githubTag:
    description: 'The semver tag of the GitHub Release'
    required: false

outputs:
  changeCaseId:
    description: Id for the change case created
    value: ${{ steps.ctc.outputs.ctcId }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: npm

    - run: npm install -g @salesforce/change-case-management --omit=dev
      shell: bash

    - name: Open CTC case
      id: ctc
      uses: salesforcecli/github-workflows/.github/actions/retry@main
      with:
        max_attempts: 5
        command: |
          if [ -n "$GITHUB_TAG" ]; then
            RELEASE_URL="${{ github.server_url }}/${{ github.repository }}/releases/tag/$GITHUB_TAG"
          else
            RELEASE_URL="${{ github.server_url }}/${{ github.repository }}/releases"
          fi
          CTC_RESULT=$(sfchangecase create --location ${{github.repositoryUrl}} --test-environment $RELEASE_URL --service platform-cli --release ${{github.repository}}.$(date +%F) --json)

          STATUS=$(printf '%s' "$CTC_RESULT" | jq -r '.status')
          CTC_ID=$(printf '%s' "$CTC_RESULT" | jq -r '.result.id')

          if [[ "$STATUS" == "0" && "$CTC_ID" != "null" ]]; then
              echo "Successfully created case with ID: $CTC_ID"
              echo "ctcId=$CTC_ID" >> "$GITHUB_OUTPUT"
          else
              echo "CTC failed to open a case. Result:"
              echo "$CTC_RESULT"
              exit 1
          fi
      env:
        SF_CHANGE_CASE_SFDX_AUTH_URL: ${{ inputs.SF_CHANGE_CASE_SFDX_AUTH_URL}}
        SF_CHANGE_CASE_TEMPLATE_ID: ${{ inputs.SF_CHANGE_CASE_TEMPLATE_ID}}
        SF_CHANGE_CASE_CONFIGURATION_ITEM: ${{ inputs.SF_CHANGE_CASE_CONFIGURATION_ITEM}}
        GITHUB_TAG: ${{ inputs.githubTag }}

    - run: echo "[INFO] Change Case ID is:\ $STEPS_CTC_CTCID"
      shell: bash
      env:
        STEPS_CTC_CTCID: ${{ steps.ctc.outputs.ctcId }}
