on:
  workflow_call:
    inputs:
      githubTag:
        description: 'The semver tag of the GitHub Release'
        type: string
    outputs:
      changeCaseId:
        description: Id for the change case created
        value: ${{ jobs.ctcOpen.outputs.changeCaseId }}

jobs:
  ctcOpen:
    outputs:
      changeCaseId: ${{ steps.ctc.outputs.ctcId }}
    runs-on: static-ip-ubuntu-runners
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - run: npm install -g @salesforce/change-case-management --omit=dev

      - name: Open CTC case
        id: ctc
        shell: bash
        run: |
            # Temp disable exit on error
            set +e
            if [ -n "$GITHUB_TAG" ]; then
              RELEASE_URL="${{ github.server_url }}/${{ github.repository }}/releases/tag/$GITHUB_TAG"
            else
              RELEASE_URL="${{ github.server_url }}/${{ github.repository }}/releases"
            fi
            CTC_RESULT=$(sfchangecase create --location ${{github.repositoryUrl}} --test-environment $RELEASE_URL --release ${{github.repository}}.$(date +%F) --json)
            # Re-enable exit on error
            set -e

            STATUS=$(printf '%s' "$CTC_RESULT" | jq -r '.status')
            CTC_ID=$(printf '%s' "$CTC_RESULT" | jq -r '.result.id')

            if [[ "$STATUS" == "0" && "$CTC_ID" != "null" ]]; then
                echo "Successfully created case with ID: $CTC_ID"
                echo "ctcId=$CTC_ID" >> "$GITHUB_OUTPUT"
            else
                echo "CTC failed to open a case. Result:"
                echo "$CTC_RESULT"
                exit 1
            fi
        env:
          GITHUB_TAG: ${{ inputs.githubTag }}
          SF_CHANGE_CASE_SFDX_AUTH_URL: ${{ secrets.SF_CHANGE_CASE_SFDX_AUTH_URL}}
          SF_CHANGE_CASE_TEMPLATE_ID: ${{ secrets.SF_CHANGE_CASE_TEMPLATE_ID}}
          SF_CHANGE_CASE_CONFIGURATION_ITEM: ${{ secrets.SF_CHANGE_CASE_CONFIGURATION_ITEM}}

      - run: echo "[INFO] Change Case ID is:\ $STEPS_CTC_ID"
        env:
          STEPS_CTC_ID: ${{ steps.ctc.outputs.ctcId }}
