on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: version for upload. do not include the 'v'
      channel:
        type: string
        required: true
        description: channel that the uploaded tarballs get promoted to
      nodeVersion:
        type: string
        default: lts/*
        description: node version to use for the tarball build
jobs:
  macos:
    env:
      SF_DISABLE_TELEMETRY: true
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}
          cache: yarn

      - uses: salesforcecli/github-workflows/.github/actions/yarnInstallWithRetries@main

      - name: Pack for macos
        uses: salesforcecli/github-workflows/.github/actions/retry@main
        with:
          command: yarn pack:macos

      - name: Upload macos
        run: yarn upload:macos
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Promote macos to ${{ inputs.channel }} channel
        run: yarn channel:promote --cli sf --version "$INPUTS_VERSION" --target "$INPUTS_CHANNEL" --platform macos
        env:
          INPUTS_VERSION: ${{ inputs.version }}
          INPUTS_CHANNEL: ${{ inputs.channel }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload artifacts to Github release
        run: gh release upload "$INPUTS_VERSION" ./dist/macos/sf-*.pkg --clobber --repo "$GIT_REPOSITORY"
        env:
          INPUTS_VERSION: ${{ inputs.version }}
          GH_TOKEN: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
