on: workflow_call

jobs:
  prevent-typescript-dependency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - run: |
          yarn install --production
          if [ -d node_modules/typescript ]; then
            echo "ERROR: Typescript dependency found";
            echo "--- yarn why typescript ---"
            yarn why typescript;
            echo "--- npm ls typescript---"
            npm ls typescript
            exit 1;
          fi
