on:
  workflow_call:
    inputs:
      upload:
        type: boolean
        description: true means test, then upload them AWS
        required: false
      version:
        type: string
        required: false
        description: version for upload. do not include the 'v'
      channel:
        type: string
        required: false
        description: channel that the uploaded tarballs get promoted to
      nodeVersion:
        type: string
        default: lts/*
        description: node version to use for the tarball build

jobs:
  tarballs:
    env:
      SF_DISABLE_TELEMETRY: true
    runs-on: ubuntu-22-8core
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}
          cache: yarn

      - uses: salesforcecli/github-workflows/.github/actions/yarnInstallWithRetries@main

      - name: pack tarballs
        uses: salesforcecli/github-workflows/.github/actions/retry@main
        with:
          command: yarn pack:tarballs
          retry_on: error

      - run: yarn pack:verify

      - run: yarn test:smoke-unix

      - if: inputs.upload
        run: yarn upload:tarballs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - if: inputs.upload && inputs.version && inputs.channel
        run: yarn channel:promote --cli sf --version "$INPUTS_VERSION" --target "$INPUTS_CHANNEL"
        env:
          INPUTS_VERSION: ${{ inputs.version }}
          INPUTS_CHANNEL: ${{ inputs.channel }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - if: inputs.upload
        run: |
          gh release upload "$INPUTS_VERSION" ./dist/*.gz --clobber --repo "$GITHUB_REPOSITORY"
          gh release upload "$INPUTS_VERSION" ./dist/*.xz --clobber --repo "$GITHUB_REPOSITORY"
        env:
          INPUTS_VERSION: ${{ inputs.version }}
          GH_TOKEN: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}